name: build-labeler
version: '${project.version}'
main: me.gwerneckp.buildlabeler.Build_labeler
api-version: '1.20'
authors: [Gabriel Werneck]
description: This plugin is used to help collect labelled schematics of Minecraft buildings to them use them to train a ML model.
