name: BuildLabeler
version: '${project.version}'
main: me.gwerneckp.buildlabeler.BuildLabeler
api-version: '1.20'
depend: [ WorldEdit ]
authors: [ Gabriel Werneck ]
description: This plugin is used to help collect labelled schematics of Minecraft buildings to them use them to train a ML model.
