name: BuildLabeler
version: '${project.version}'
main: me.gwerneckp.buildlabeler.BuildLabeler
api-version: '1.20'
authors: [ Gabriel Werneck ]
depend: [ WorldEdit, WorldGuard, WorldGuardExtraFlags ]
description: This plugin is used to help collect labelled schematics of Minecraft buildings to them use them to train a ML model.'
commands:
  build:
    description: 'Start a new build session.'
    aliases: [ build, buildlabeler, construir, construire ]
    usage: "/build"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  clean:
    description: 'Clean the current build session.'
    aliases: [ clean, cleanlabeler, limpar, vider ]
    usage: "/clean"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  end:
    description: 'End the current build session.'
    aliases: [ end, endlabeler, terminar, arreter, terminer ]
    usage: "/end"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  theme:
    description: 'Set the theme of the current build session.'
    aliases: [ label, labellabeler, tema ]
    usage: "/label <label>"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  randomtheme:
    description: 'Get a new random theme.'
    aliases: [ randomlabel, randomlabellabeler, temaaleatorio, themerandom, randomtheme, random, themealeatoire, aleatoire, aleatorio ]
    usage: "/randomlabel"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  submit:
    description: 'Submit the current build session.'
    aliases: [ submit, submitlabeler, submeter, soumettre, enviar ]
    usage: "/submit"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.build
  language:
    description: 'Change the language of the plugin.'
    aliases: [ language, languagelabeler, idioma, langue ]
    usage: "/language <language>"
    permission-message: You don't have permission to use this command.
  getworlds:
    description: 'Get the list of worlds.'
    aliases: [ getworlds, worlds ]
    usage: "/getworlds"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.dev
  gotoworld:
    description: 'Teleport to a world.'
    aliases: [ gotoworld, goto ]
    usage: "/gotoworld <world>"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.dev
  createlobby:
    description: 'Create a lobby world.'
    aliases: [ createlobby, createlobbyworld ]
    usage: "/createlobby"
    permission-message: You don't have permission to use this command.
    permission: buildlabeler.dev