name: BuildLabeler
version: '1.0-SNAPSHOT'
main: me.gwerneckp.buildlabeler.BuildLabeler
api-version: '1.20'
authors: [ Gabriel Werneck ]
depend: [ WorldEdit, WorldGuard, WorldGuardExtraFlags ]
description: This plugin is used to help collect labelled schematics of Minecraft buildings to them use them to train a ML model.'
commands:
  build:
    description: 'Start a new build session.'
    aliases: [ build, buildlabeler ]
    usage: "/build"
    permission-message: You don't have permission to use this command.
  clean:
    description: 'Clean the current build session.'
    aliases: [ clean, cleanlabeler ]
    usage: "/clean"
    permission-message: You don't have permission to use this command.
  end:
    description: 'End the current build session.'
    aliases: [ end, endlabeler ]
    usage: "/end"
    permission-message: You don't have permission to use this command.
  label:
    description: 'Label the current build session.'
    aliases: [ label, labellabeler ]
    usage: "/label <label>"
    permission-message: You don't have permission to use this command.
  randomlabel:
    description: 'Get a new random label.'
    aliases: [ randomlabel, randomlabellabeler ]
    usage: "/randomlabel"
    permission-message: You don't have permission to use this command.
  submit:
    description: 'Submit the current build session.'
    aliases: [ submit, submitlabeler ]
    usage: "/submit"
    permission-message: You don't have permission to use this command.
