name: BuildLabeler
version: '1.0-SNAPSHOT'
main: me.gwerneckp.buildlabeler.BuildLabeler
api-version: '1.20'
authors: [ Gabriel Werneck ]
depend: [ WorldEdit, WorldGuard, WorldGuardExtraFlags ]
description: This plugin is used to help collect labelled schematics of Minecraft buildings to them use them to train a ML model.'
commands:
  build:
    description: 'Start a new build session.'
    aliases: [ build, buildlabeler ]
    usage: "/build"
    permission-message: You don't have permission to use this command.
  clear:
    description: 'Clear the current build session.'
    aliases: [ clear, clearlabeler ]
    usage: "/clear"
    permission-message: You don't have permission to use this command.
  end:
    description: 'End the current build session.'
    aliases: [ end, endlabeler ]
    usage: "/end"
    permission-message: You don't have permission to use this command.
  label:
    description: 'Label the current build session.'
    aliases: [ label, labellabeler ]
    usage: "/label <label>"
    permission-message: You don't have permission to use this command.
  newlabel:
    description: 'Get a new random label.'
    aliases: [ newlabel, newlabellabeler ]
    usage: "/newlabel"
    permission-message: You don't have permission to use this command.
  submit:
    description: 'Submit the current build session.'
    aliases: [ submit, submitlabeler ]
    usage: "/submit"
    permission-message: You don't have permission to use this command.
